FROM node:16.16-alpine
USER node
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node package*.json .

# Install dependencies
RUN npm install

# Copy sources
COPY --chown=node:node . .

EXPOSE 3000
